"""make_user_name_unique

Revision ID: 2b1ec6ace320
Revises: d1e2f3a4b5c6
Create Date: 2026-03-16 17:04:01.299619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2b1ec6ace320'
down_revision: Union[str, Sequence[str], None] = 'd1e2f3a4b5c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_name', 'user', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'invite_code',
               existing_type=mysql.VARCHAR(length=9),
               nullable=True)
    op.drop_constraint("uq_user_name", "user", type_="unique")
    # ### end Alembic commands ###
