"""initial

Revision ID: 34ea8ec03198
Revises: 
Create Date: 2026-03-09 13:01:34.668961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '34ea8ec03198'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('test', sa.Column('message', sa.String(length=100), nullable=False))
    op.drop_column('test', 'ID')
    op.drop_column('test', 'Message')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('Message', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('test', sa.Column('ID', mysql.SMALLINT(unsigned=True), autoincrement=True, nullable=False))
    op.drop_column('test', 'message')
    op.drop_column('test', 'id')
    # ### end Alembic commands ###
